sudo: required
services:
  - docker

before_install:
  - docker build -t aicha/docker-react -f Dockerfile.dev .
#the -- --coverage to exit after the tests are completed because npm run test doesnt exit
script:
  - docker run  aicha/docker-react npm run test -- --coverage
